#!/bin/bash
# DDMSDocs | Responses.sh

set -o posix

# This file was generated by dsh.
# This file defines the DDMSDocs App Package's configuration variables.
# For more information about this file use: dsh -h -n AppPackage config.sh

######################## Configuration Settings ########################

app_name="DDMSDocs"

bug_contact="contact not provided"

config_locked="0"

declare -A dependencies
dependencies=()

description="The DDMSDocs App was developed for the Darling Data Management System."

developers=()

development_port="PORT"

documentation="DOCUMENTATION_SOURCE"

domain="https://localhost:8973"

license="MIT"

version="0.0.0"

version_date="unknown"

