#!/bin/bash
# FariesAR | Responses.sh

set -o posix

# This file was generated by dsh.
# This file defines the FariesAR App Package's configuration variables.
# For more information about this file use: dsh -h -n AppPackage config.sh

######################## Configuration Settings ########################

app_name="FariesAR"

bug_contact="sdmwebsdm@gmail.com"

config_locked="0"

declare -A dependencies
dependencies=( ["HtmlStructure"]="0.0.0" )

description="The FariesAR App was developed for the Darling Data Management System."

developers=( "Sevi Donnelly Foreman" )

development_port="8080"

documentation="self-documented"

domain="http://localhost:8080"

license="MIT"

version="0.0.0"

version_date="2021-01-06"

